export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const HIDE_PROGRESS = 'HIDE_PROGRESS';

export const SET_TOKEN = 'SET_TOKEN';
export const SET_USERTYPE = 'SET_USERTYPE';
export const SET_USERDATA = 'SET_USERDATA';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PHONENUMBER = 'SET_PHONENUMBER';
export const SET_AREAS = 'SET_AREAS';
export const SET_AREACODES = 'SET_AREACODES';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';

export const SET_MARKERLIST = 'SET_MARKERLIST';
export const SET_DONELIST = 'SET_DONELIST';
export const SET_SELECTEDMARKER = 'SET_SELECTEDMARKER';
export const SET_CENTERCOORDS = 'SET_CENTERCOORDS';
export const SET_NEXTDOWNLOAD = 'SET_NEXTDOWNLOAD';
export const SET_MAPNAVIGATION = 'SET_MAPNAVIGATION';
export const SET_STOPCOLOR = 'SET_STOPCOLOR';
export const SET_DOWNLOADSTATES = 'SET_DOWNLOADSTATES';


export const SET_DRIVERPERFORMANCE = 'SET_DRIVERPERFORMANCE';